// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62nOVdKr6q9sycr7DOwiS2v_eDnDKZYU',
    appId: '1:460970537341:web:0298c898e1ba90f2f11c14',
    messagingSenderId: '460970537341',
    projectId: 'campus-ede23',
    authDomain: 'campus-ede23.firebaseapp.com',
    storageBucket: 'campus-ede23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLjm5Yycs8TuwO0H4gVJTgyGF9QQqXT0',
    appId: '1:460970537341:android:6d43705d7102bfc1f11c14',
    messagingSenderId: '460970537341',
    projectId: 'campus-ede23',
    storageBucket: 'campus-ede23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr1wZvt2G-cRESbgglANjnasyIdHTyY3o',
    appId: '1:460970537341:ios:6dfa64eb744a1bd2f11c14',
    messagingSenderId: '460970537341',
    projectId: 'campus-ede23',
    storageBucket: 'campus-ede23.firebasestorage.app',
    iosBundleId: 'com.example.mantenimientoCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr1wZvt2G-cRESbgglANjnasyIdHTyY3o',
    appId: '1:460970537341:ios:6dfa64eb744a1bd2f11c14',
    messagingSenderId: '460970537341',
    projectId: 'campus-ede23',
    storageBucket: 'campus-ede23.firebasestorage.app',
    iosBundleId: 'com.example.mantenimientoCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62nOVdKr6q9sycr7DOwiS2v_eDnDKZYU',
    appId: '1:460970537341:web:fa3aeeb18c7336e6f11c14',
    messagingSenderId: '460970537341',
    projectId: 'campus-ede23',
    authDomain: 'campus-ede23.firebaseapp.com',
    storageBucket: 'campus-ede23.firebasestorage.app',
  );
}
